pull_request_rules:
  - name: Automatic merge when dependencies are updated and build is successful
    update_method: merge
    conditions:
      - label=dependencies
      - check-success=Build
      - author=dependabot[bot]
    actions:
      merge:
        method: squash
