pull_request_rules:
  - name: Automatic merge when dependencies are updated and build is successful
    conditions:
      - and:
        - label=dependencies
        - author=dependabot[bot]
        - approved-reviews-by>=1
    actions:
      merge:
        method: squash
queue_rules:
  - name: default
    batch_size: 1
    batch_max_wait_time: 10 min
    merge_method: squash
