name: Local Code Coverage

on: [pull_request]

jobs:
  base_branch_cov:
    if: github.event.pull_request.draft == true
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - uses: extractions/setup-just@v2
      - name: Run tests
        run: |
          just test-ci
          mv coverage.lcov coverage-ref.lcov
      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v4
        with:
          name: coverage-ref.lcov
          path: coverage-ref.lcov

  checks:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: base_branch_cov
    steps:
    - uses: actions/checkout@v4

    - name: Download code coverage report from base branch
      uses: actions/download-artifact@v4
      with:
        name: coverage-ref.lcov

    - run: ls -la
    - name: Install Python 3.12
      uses: actions/setup-python@v5
      with:
          python-version: '3.12'
          cache: 'pip'
    - uses: extractions/setup-just@v2
    - name: Run tests
      run: |
              just test-ci
#  Compares two code coverage files and generates report as a comment
    - name: Generate Code Coverage report
      id: code-coverage
      uses: barecheck/code-coverage-action@v1
      with:
        barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
        lcov-file: "coverage.lcov"
        base-lcov-file: "coverage-ref.lcov"
        minimum-ratio: 50
        send-summary-comment: true
        show-annotations: "warning" # Possible options warning|error
        github-token: ${{ secrets.GITHUB_TOKEN }}
